services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: lingofusion-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: lingofusion-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
