defaults:
  - _self_
  - translation

mode: translation

seed: 42

data:
  raw: data/raw
  processed: data/processed

training:
  epochs: 3
  batch_size: 32
  lr: 3e-5

hydra:
  run:
    dir: ${hydra:runtime.cwd}
  job:
    chdir: false
